### ISSUE TITLE
Does not allow you to go to other players

### ISSUE THREAD

**Issue by ghost** [MegaPiggy/LethalCompanyBuyableShotgunShells#1]
### What Happened?

I updated this mod to version 1.0.4 and after that I can't connect to anyone and no one can connect to me. Everything worked stably on version 1.0.3. Please, my developer friend, fix the mod, it is the most useful of all for me!
Thank you for this mod and wish you good luck!

### What was supposed to happen?

I was supposed to connect to a friend, but I couldn't do it.
I tried to others, but also without result(

### Game version

v49

### Mods

```Markdown
My Mods: BepInExPack, Minimap, LateCompany, BetterItemScan, More_Emotes, Helmet_Cameras, Custom_Boombox_Music, LethalLib, HookGenPatcher, Runtime_Netcode_Patcher and BuyableShotgunShells
```
```018d3dac-710e-9a5a-f2ba-69c4a941bc25```

### Logs

```Shell
In version 1.0.4, since yesterday, everything worked stably on version 1.0.3
```

**Comment by PC-Principal** [comment]
> ### What Happened?
> I updated this mod to version 1.0.4 and after that I can't connect to anyone and no one can connect to me. Everything worked stably on version 1.0.3. Please, my developer friend, fix the mod, it is the most useful of all for me! Thank you for this mod and wish you good luck!
> 
> ### What was supposed to happen?
> I was supposed to connect to a friend, but I couldn't do it. I tried to others, but also without result(
> 
> ### Game version
> v49
> 
> ### Mods
> ```
> My Mods: BepInExPack, Minimap, LateCompany, BetterItemScan, More_Emotes, Helmet_Cameras, Custom_Boombox_Music, LethalLib, HookGenPatcher, Runtime_Netcode_Patcher and BuyableShotgunShells
> ```
> 
> ### Logs
> ```shell
> In version 1.0.4, since yesterday, everything worked stably on version 1.0.3
> ```

Agree and test it - there is actual problem for now

**Comment by MegaPiggy** [comment]
Can't reproduce this. I joined someone with both of us having the mod list you provided and everything worked fine.
![Looking at the host](https://github.com/MegaPiggy/LethalCompanyBuyableShotgunShells/assets/34462599/9c4f8035-25d2-47a9-948f-d46b2158d40f)
![Looking at terminal store](https://github.com/MegaPiggy/LethalCompanyBuyableShotgunShells/assets/34462599/a4db3e3d-d6d2-4222-8b1b-1b25fb62a14e)
